name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Set up Java toolchain
        uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build
        run: |
          pwd
          export GRADLE_USER_HOME=$(pwd)/.gradle
          gradle wrapper
          ./gradlew assemble
          ls
        working-directory: BalanceKeranjangBelanjaHistoryRating

      - name: Upload Build Artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: BalanceKeranjangBelanjaHistoryRating/build/libs/*.jar

  test:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Set up Java toolchain
        uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Test
        run: |
          pwd
          export GRADLE_USER_HOME=$(pwd)/.gradle
          export SPRING_PROFILES_ACTIVE=test
          gradle check --info --stacktrace
          gradle test
          gradle jacocoTestReport
          grep -Eo "Total.*?([0-9]{1,3})%" build/jacocoHtml/index.html
        working-directory: BalanceKeranjangBelanjaHistoryRating

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: BalanceKeranjangBelanjaHistoryRating/build/test-results/test/**/*.xml