name: "Sonarcloud Scanning"

on:
  pull_request:
    branches:
      - dev
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -   uses: actions/checkout@v3
          with:
            fetch-depth: 0
      -   name: Set up JDK 21
          uses: actions/setup-java@v3
          with:
            distribution: 'temurin'
            java-version: '21'
      -   name: Make ./gradlew executable
          run: chmod +x ./gradlew
      -   name: Build with Gradle without test
          run: ./gradlew build -x test
      -   name: SonarCloud Scan
          uses: sonarsource/sonarcloud-github-action@master
          env:
            GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          with:
            args: >
              -Dsonar.organization=advpro-2024-a13
              -Dsonar.projectKey=advpro-2024-a13_Food-Groceries-Supermarket-Product
              -Dsonar.java.binaries=build/classes/java/main/heymart/backend,build/classes/java/main/heymart/backend/models,build/classes/java/main/heymart/backend/controller,build/classes/java/main/heymart/backend/repository,build/classes/java/main/heymart/backend/service
              -Dsonar.java.libraries=build/libs/*.jar
              -Dsonar.gradle.skipCompile=true
              -Dsonar.java.test.binaries=build/classes/java/test/heymart/backend,build/classes/java/test/heymart/backend/models,build/classes/java/test/heymart/backend/controller,build/classes/java/test/heymart/backend/repository,build/classes/java/test/heymart/backend/service
              -Dsonar.junit.reportPaths=build/test-results/test
              -Dsonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml