name: SonarCloud analysis

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

permissions:
  pull-requests: read # allows SonarCloud to decorate PRs with analysis results

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
        - name: Check out the Git repository
          uses: actions/checkout@v4

        - name: Set up Java toolchain
          uses: actions/setup-java@v4
          with:
            distribution: "temurin"
            java-version: "21"
            cache: "gradle"

        - name: Set gradlew as executable
          run: chmod +x ./gradlew

        - name: Build with Gradle
          run: ./gradlew build

        - name: Analyze with SonarCloud
          uses: sonarsource/sonarcloud-github-action@master
          env:
            GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          with:
            args: >
              -Dsonar.organization=advpro-2024-a13
              -Dsonar.projectKey=advpro-2024-a13_Food-Groceries-Supermarket-Product
              -Dsonar.java.binaries=build/classes/java/main/heymart/backend,build/classes/java/main/heymart/backend/models,build/classes/java/main/heymart/backend/controller,build/classes/java/main/heymart/backend/repository,build/classes/java/main/heymart/backend/service
              -Dsonar.sources=src/main/java
              -Dsonar.tests=src/test/java